Algoritmo "Média das notas"

Var
   Nome: Caracter
   Nota1, Nota2, M: Real

Inicio
      Escreval("Descubra a média das duas notas")
      Escreva("Qual o seu nome? ")
      Leia(Nome)
      Escreva("Qual a primeira nota? ")
      Leia(Nota1)
      Escreva("Qual a segunda nota? ")
      Leia(Nota2)
      M <- (Nota1 + Nota2)/2
      Escreva(Nome," a sua média será de ",M)


Fimalgoritmo